Information:
  Title: Ellie's Blog
  Icon: icon.png
  Description: Ellie's Blog for her rants and other stuff.
  Link: pnk.wtf
  Theme: Default

Connections:
  GitHub: samsucksatcoding
  GitLab: 
  Bluesky: 
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
